### ISSUE TITLE
Question about SXM2 vs SXM3 ? 

### ISSUE THREAD

**Issue by JGuillaumin** [l4rz/running-nvidia-sxm-gpus-in-consumer-pcs#1]
Hi, 
Your projects with SXM chips connected with PCI sockets are impressive. 
Since you seem to have a lot of knowledge about this kind of connectors, can I ask you a related question that I have for few weeks ? 

I have a server with SXM2 sockets with Tesla P100 16GB SXM2. Can I replace the P100 by V100 32GB which are for SXM3 ? 
From what I understood, SXM2 and SXM3 are physically identical (pin connectors), but SXM3 socket can deliver more power (48V instead of 12V). Is it an issue for the V100 ? First series of V100, with 16GB, were for SXM2. 

Best regards, 
Julien

**Comment by l4rz** [comment]
Hi Julien

No, it's not possible to replace SXM2 P100s with SXM3 V100s - the SXM mezzanine connectors are completely different. You can replace P100s with SXM2 V100s; depending on server type, you need to keep in mind the throttling issues that might arise if the 32Gb V100 is not in list of vendor-approved GPUs for this particular server.

For example, for Dell C4130 P100s can be replaced with 32Gb V100s (with some iDRAC patching...).

Sincerely,
Mike

**Comment by JGuillaumin** [comment]
Hi Mike, 

Thank you very much for your quick answer. 
I will stay with my P100s longer :) 

Best regards,
Julien
